name: Compile Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install typst-cli && typst compile resume.typ --input admin=true --input developer=true   
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
            resume.pdf
